name: Refresh Stats

on:
  schedule:
    - cron: "0 0 * * *" # 每天午夜触发
  workflow_dispatch: # 手动触发

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Update README
        run: echo "Triggered cache refresh at $(date)"
